# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/image_filter/image_filter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter || ORIG_REF_NAME==image_filter} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_dma_0_0/image_filter_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_dma_0_0 || ORIG_REF_NAME==image_filter_axi_dma_0_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_smc_0/image_filter_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_smc_0 || ORIG_REF_NAME==image_filter_axi_smc_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_rst_ps7_0_100M_0/image_filter_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_rst_ps7_0_100M_0 || ORIG_REF_NAME==image_filter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_mem_intercon_imp_xbar_0/image_filter_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==image_filter_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_mem_intercon_0/image_filter_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_mem_intercon_0 || ORIG_REF_NAME==image_filter_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_processing_system7_0_1/image_filter_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_processing_system7_0_1 || ORIG_REF_NAME==image_filter_processing_system7_0_1} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_acc_image_filter_0_2/image_filter_acc_image_filter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_acc_image_filter_0_2 || ORIG_REF_NAME==image_filter_acc_image_filter_0_2} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_timer_0_0/image_filter_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_timer_0_0 || ORIG_REF_NAME==image_filter_axi_timer_0_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_xlconcat_0_2/image_filter_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_xlconcat_0_2 || ORIG_REF_NAME==image_filter_xlconcat_0_2} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_us_0/image_filter_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==image_filter_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_us_1/image_filter_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==image_filter_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_pc_0/image_filter_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==image_filter_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==image_filter_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/kowalski/Desktop/ETF/CETVRTA-GODINA/DVS/dvs25_projekat_g6/dvs25_projekat_g6.gen/sources_1/bd/image_filter/image_filter_ooc.xdc
