set_property SRC_FILE_INFO {cfile:/home/kowalski/Desktop/ETF/CETVRTA-GODINA/DVS/dvs25_projekat_g6/dvs25_projekat_g6.srcs/constrs_1/new/debug_cores.xdc rfile:../../../dvs25_projekat_g6.srcs/constrs_1/new/debug_cores.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[13]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[14]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[15]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[2]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[3]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[4]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[5]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[6]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[7]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[8]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[9]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[10]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[11]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/m_axis_tdata[12]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/m_axis_tvalid]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_arready]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/m_axis_tlast]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_awready]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_bvalid]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[1]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[15]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[13]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[14]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[11]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[12]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[2]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[3]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[4]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[5]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[6]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[7]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[8]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[9]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[10]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_rvalid]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_wready]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axis_tready]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axis_tvalid]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axis_tlast]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[0]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[1]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[2]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[3]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[4]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[5]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[6]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axis_tdata[7]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_wvalid]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wstrb[0]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wstrb[1]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[2]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[0]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[1]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[14]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[15]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[12]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[13]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[3]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[4]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[5]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[6]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[7]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[8]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[9]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[10]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[11]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_rready]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_bready]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/s_axi_ctrl_awvalid]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/<const0>]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets image_filter_i/acc_image_filter_0/m_axis_tready]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list image_filter_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[0]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[1]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[2]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[3]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[4]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[5]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[6]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[7]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[8]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[9]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[10]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[11]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[12]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[13]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[14]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wdata[15]}]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {image_filter_i/acc_image_filter_0/U0/tvalid_fifo[0]} {image_filter_i/acc_image_filter_0/U0/tvalid_fifo[1]} {image_filter_i/acc_image_filter_0/U0/tvalid_fifo[2]} {image_filter_i/acc_image_filter_0/U0/tvalid_fifo[3]} {image_filter_i/acc_image_filter_0/U0/tvalid_fifo[4]} {image_filter_i/acc_image_filter_0/U0/tvalid_fifo[5]}]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {image_filter_i/acc_image_filter_0/m_axis_tdata[0]} {image_filter_i/acc_image_filter_0/m_axis_tdata[1]} {image_filter_i/acc_image_filter_0/m_axis_tdata[2]} {image_filter_i/acc_image_filter_0/m_axis_tdata[3]} {image_filter_i/acc_image_filter_0/m_axis_tdata[4]} {image_filter_i/acc_image_filter_0/m_axis_tdata[5]} {image_filter_i/acc_image_filter_0/m_axis_tdata[6]} {image_filter_i/acc_image_filter_0/m_axis_tdata[7]} {image_filter_i/acc_image_filter_0/m_axis_tdata[8]} {image_filter_i/acc_image_filter_0/m_axis_tdata[9]} {image_filter_i/acc_image_filter_0/m_axis_tdata[10]} {image_filter_i/acc_image_filter_0/m_axis_tdata[11]} {image_filter_i/acc_image_filter_0/m_axis_tdata[12]} {image_filter_i/acc_image_filter_0/m_axis_tdata[13]} {image_filter_i/acc_image_filter_0/m_axis_tdata[14]} {image_filter_i/acc_image_filter_0/m_axis_tdata[15]}]]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[0]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[1]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[2]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[3]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[4]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[5]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[6]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[7]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[8]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[9]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[10]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[11]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[12]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[13]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[14]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_rdata[15]}]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {image_filter_i/acc_image_filter_0/s_axis_tdata[0]} {image_filter_i/acc_image_filter_0/s_axis_tdata[1]} {image_filter_i/acc_image_filter_0/s_axis_tdata[2]} {image_filter_i/acc_image_filter_0/s_axis_tdata[3]} {image_filter_i/acc_image_filter_0/s_axis_tdata[4]} {image_filter_i/acc_image_filter_0/s_axis_tdata[5]} {image_filter_i/acc_image_filter_0/s_axis_tdata[6]} {image_filter_i/acc_image_filter_0/s_axis_tdata[7]}]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {image_filter_i/acc_image_filter_0/s_axi_ctrl_wstrb[0]} {image_filter_i/acc_image_filter_0/s_axi_ctrl_wstrb[1]}]]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {image_filter_i/acc_image_filter_0/U0/tlast_fifo[0]} {image_filter_i/acc_image_filter_0/U0/tlast_fifo[1]} {image_filter_i/acc_image_filter_0/U0/tlast_fifo[2]} {image_filter_i/acc_image_filter_0/U0/tlast_fifo[3]} {image_filter_i/acc_image_filter_0/U0/tlast_fifo[4]} {image_filter_i/acc_image_filter_0/U0/tlast_fifo[5]}]]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {image_filter_i/acc_image_filter_0/U0/sA_data[0]} {image_filter_i/acc_image_filter_0/U0/sA_data[1]} {image_filter_i/acc_image_filter_0/U0/sA_data[2]} {image_filter_i/acc_image_filter_0/U0/sA_data[3]} {image_filter_i/acc_image_filter_0/U0/sA_data[4]} {image_filter_i/acc_image_filter_0/U0/sA_data[5]} {image_filter_i/acc_image_filter_0/U0/sA_data[6]} {image_filter_i/acc_image_filter_0/U0/sA_data[7]}]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {image_filter_i/acc_image_filter_0/U0/reg_radius[0]} {image_filter_i/acc_image_filter_0/U0/reg_radius[1]} {image_filter_i/acc_image_filter_0/U0/reg_radius[2]} {image_filter_i/acc_image_filter_0/U0/reg_radius[3]} {image_filter_i/acc_image_filter_0/U0/reg_radius[4]} {image_filter_i/acc_image_filter_0/U0/reg_radius[5]} {image_filter_i/acc_image_filter_0/U0/reg_radius[6]} {image_filter_i/acc_image_filter_0/U0/reg_radius[7]} {image_filter_i/acc_image_filter_0/U0/reg_radius[8]} {image_filter_i/acc_image_filter_0/U0/reg_radius[9]} {image_filter_i/acc_image_filter_0/U0/reg_radius[10]} {image_filter_i/acc_image_filter_0/U0/reg_radius[11]} {image_filter_i/acc_image_filter_0/U0/reg_radius[12]} {image_filter_i/acc_image_filter_0/U0/reg_radius[13]} {image_filter_i/acc_image_filter_0/U0/reg_radius[14]} {image_filter_i/acc_image_filter_0/U0/reg_radius[15]}]]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {image_filter_i/acc_image_filter_0/U0/reg_output[0]} {image_filter_i/acc_image_filter_0/U0/reg_output[1]} {image_filter_i/acc_image_filter_0/U0/reg_output[2]} {image_filter_i/acc_image_filter_0/U0/reg_output[3]} {image_filter_i/acc_image_filter_0/U0/reg_output[4]} {image_filter_i/acc_image_filter_0/U0/reg_output[5]} {image_filter_i/acc_image_filter_0/U0/reg_output[6]} {image_filter_i/acc_image_filter_0/U0/reg_output[7]} {image_filter_i/acc_image_filter_0/U0/reg_output[8]} {image_filter_i/acc_image_filter_0/U0/reg_output[9]} {image_filter_i/acc_image_filter_0/U0/reg_output[10]} {image_filter_i/acc_image_filter_0/U0/reg_output[11]} {image_filter_i/acc_image_filter_0/U0/reg_output[12]} {image_filter_i/acc_image_filter_0/U0/reg_output[13]} {image_filter_i/acc_image_filter_0/U0/reg_output[14]} {image_filter_i/acc_image_filter_0/U0/reg_output[15]}]]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {image_filter_i/acc_image_filter_0/U0/reg_img_w[0]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[1]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[2]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[3]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[4]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[5]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[6]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[7]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[8]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[9]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[10]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[11]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[12]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[13]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[14]} {image_filter_i/acc_image_filter_0/U0/reg_img_w[15]}]]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {image_filter_i/acc_image_filter_0/U0/reg_img_h[0]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[1]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[2]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[3]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[4]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[5]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[6]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[7]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[8]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[9]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[10]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[11]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[12]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[13]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[14]} {image_filter_i/acc_image_filter_0/U0/reg_img_h[15]}]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {image_filter_i/acc_image_filter_0/U0/reg_ctrl[0]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[1]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[2]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[3]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[4]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[5]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[6]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[7]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[8]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[9]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[10]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[11]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[12]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[13]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[14]} {image_filter_i/acc_image_filter_0/U0/reg_ctrl[15]}]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[0]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[1]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[2]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[3]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[4]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[5]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[6]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[7]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[8]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[9]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[10]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[11]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[12]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[13]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[14]} {image_filter_i/acc_image_filter_0/U0/reg_coeff_scale[15]}]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {image_filter_i/acc_image_filter_0/U0/h_img_h[0]} {image_filter_i/acc_image_filter_0/U0/h_img_h[1]} {image_filter_i/acc_image_filter_0/U0/h_img_h[2]} {image_filter_i/acc_image_filter_0/U0/h_img_h[3]} {image_filter_i/acc_image_filter_0/U0/h_img_h[4]} {image_filter_i/acc_image_filter_0/U0/h_img_h[5]} {image_filter_i/acc_image_filter_0/U0/h_img_h[6]} {image_filter_i/acc_image_filter_0/U0/h_img_h[7]} {image_filter_i/acc_image_filter_0/U0/h_img_h[8]} {image_filter_i/acc_image_filter_0/U0/h_img_h[9]} {image_filter_i/acc_image_filter_0/U0/h_img_h[10]} {image_filter_i/acc_image_filter_0/U0/h_img_h[11]} {image_filter_i/acc_image_filter_0/U0/h_img_h[12]} {image_filter_i/acc_image_filter_0/U0/h_img_h[13]} {image_filter_i/acc_image_filter_0/U0/h_img_h[14]} {image_filter_i/acc_image_filter_0/U0/h_img_h[15]}]]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {image_filter_i/acc_image_filter_0/U0/h_radius[0]} {image_filter_i/acc_image_filter_0/U0/h_radius[1]} {image_filter_i/acc_image_filter_0/U0/h_radius[2]} {image_filter_i/acc_image_filter_0/U0/h_radius[3]} {image_filter_i/acc_image_filter_0/U0/h_radius[4]} {image_filter_i/acc_image_filter_0/U0/h_radius[5]} {image_filter_i/acc_image_filter_0/U0/h_radius[6]} {image_filter_i/acc_image_filter_0/U0/h_radius[7]} {image_filter_i/acc_image_filter_0/U0/h_radius[8]} {image_filter_i/acc_image_filter_0/U0/h_radius[9]} {image_filter_i/acc_image_filter_0/U0/h_radius[10]} {image_filter_i/acc_image_filter_0/U0/h_radius[11]} {image_filter_i/acc_image_filter_0/U0/h_radius[12]} {image_filter_i/acc_image_filter_0/U0/h_radius[13]} {image_filter_i/acc_image_filter_0/U0/h_radius[14]} {image_filter_i/acc_image_filter_0/U0/h_radius[15]}]]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {image_filter_i/acc_image_filter_0/U0/img_row_counter[0]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[1]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[2]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[3]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[4]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[5]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[6]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[7]} {image_filter_i/acc_image_filter_0/U0/img_row_counter[8]}]]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {image_filter_i/acc_image_filter_0/U0/h_img_w[0]} {image_filter_i/acc_image_filter_0/U0/h_img_w[1]} {image_filter_i/acc_image_filter_0/U0/h_img_w[2]} {image_filter_i/acc_image_filter_0/U0/h_img_w[3]} {image_filter_i/acc_image_filter_0/U0/h_img_w[4]} {image_filter_i/acc_image_filter_0/U0/h_img_w[5]} {image_filter_i/acc_image_filter_0/U0/h_img_w[6]} {image_filter_i/acc_image_filter_0/U0/h_img_w[7]} {image_filter_i/acc_image_filter_0/U0/h_img_w[8]} {image_filter_i/acc_image_filter_0/U0/h_img_w[9]} {image_filter_i/acc_image_filter_0/U0/h_img_w[10]} {image_filter_i/acc_image_filter_0/U0/h_img_w[11]} {image_filter_i/acc_image_filter_0/U0/h_img_w[12]} {image_filter_i/acc_image_filter_0/U0/h_img_w[13]} {image_filter_i/acc_image_filter_0/U0/h_img_w[14]} {image_filter_i/acc_image_filter_0/U0/h_img_w[15]}]]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {image_filter_i/acc_image_filter_0/U0/h_ctrl[0]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[1]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[2]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[3]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[4]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[5]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[6]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[7]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[8]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[9]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[10]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[11]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[12]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[13]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[14]} {image_filter_i/acc_image_filter_0/U0/h_ctrl[15]}]]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {image_filter_i/acc_image_filter_0/U0/bram_col_out[0]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[1]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[2]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[3]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[4]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[5]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[6]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[7]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[8]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[9]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[10]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[11]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[12]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[13]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[14]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[15]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[16]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[17]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[18]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[19]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[20]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[21]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[22]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[23]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[24]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[25]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[26]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[27]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[28]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[29]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[30]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[31]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[32]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[33]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[34]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[35]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[36]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[37]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[38]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[39]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[40]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[41]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[42]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[43]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[44]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[45]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[46]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[47]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[48]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[49]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[50]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[51]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[52]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[53]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[54]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[55]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[56]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[57]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[58]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[59]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[60]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[61]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[62]} {image_filter_i/acc_image_filter_0/U0/bram_col_out[63]}]]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {image_filter_i/acc_image_filter_0/U0/img_col_counter[0]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[1]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[2]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[3]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[4]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[5]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[6]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[7]} {image_filter_i/acc_image_filter_0/U0/img_col_counter[8]}]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list image_filter_i/acc_image_filter_0/U0/alu_valid]]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list image_filter_i/acc_image_filter_0/U0/buff_flag]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list image_filter_i/acc_image_filter_0/U0/buff_tvalid]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list image_filter_i/acc_image_filter_0/U0/fsm_img_processing_state]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list image_filter_i/acc_image_filter_0/m_axis_tlast]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list image_filter_i/acc_image_filter_0/m_axis_tready]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list image_filter_i/acc_image_filter_0/U0/m_axis_tready]]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list image_filter_i/acc_image_filter_0/m_axis_tvalid]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list image_filter_i/acc_image_filter_0/U0/m_axis_tvalid]]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_arready]]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_awready]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_awvalid]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_bready]]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_bvalid]]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe35 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_rready]]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe36 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_rvalid]]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe37 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_wready]]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe38 [get_nets [list image_filter_i/acc_image_filter_0/s_axi_ctrl_wvalid]]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe39 [get_nets [list image_filter_i/acc_image_filter_0/s_axis_tlast]]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe40 [get_nets [list image_filter_i/acc_image_filter_0/s_axis_tready]]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe41 [get_nets [list image_filter_i/acc_image_filter_0/U0/s_axis_tready]]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list image_filter_i/acc_image_filter_0/s_axis_tvalid]]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list image_filter_i/acc_image_filter_0/U0/sA_out]]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
