#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 19 15:25:28 CEST 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_filter_alu_behav -key {Behavioral:sim_1:Functional:tb_filter_alu} -tclbatch tb_filter_alu.tcl -protoinst "protoinst_files/bd_1755.protoinst" -protoinst "protoinst_files/image_filter.protoinst" -log simulate.log"
xsim tb_filter_alu_behav -key {Behavioral:sim_1:Functional:tb_filter_alu} -tclbatch tb_filter_alu.tcl -protoinst "protoinst_files/bd_1755.protoinst" -protoinst "protoinst_files/image_filter.protoinst" -log simulate.log

