# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kowalski/Desktop/ETF/CETVRTA-GODINA/DVS/dvs25_projekat_g6/dvs25_projekat_g6.srcs/sources_1/bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_pc_0/image_filter_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'image_filter_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kowalski/Desktop/ETF/CETVRTA-GODINA/DVS/dvs25_projekat_g6/dvs25_projekat_g6.gen/sources_1/bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_pc_0/image_filter_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_filter_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/kowalski/Desktop/ETF/CETVRTA-GODINA/DVS/dvs25_projekat_g6/dvs25_projekat_g6.srcs/sources_1/bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_pc_0/image_filter_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'image_filter_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kowalski/Desktop/ETF/CETVRTA-GODINA/DVS/dvs25_projekat_g6/dvs25_projekat_g6.gen/sources_1/bd/image_filter/ip/image_filter_axi_mem_intercon_imp_auto_pc_0/image_filter_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_filter_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
